### ISSUE TITLE
Unexpectedly deleting typed characters

### ISSUE THREAD

**Issue by scottjmaddox** [maxboisvert/vim-simple-complete#11]
Open a new buffer, press the following key sequence:

```
iaaa111_aa<C-c>
```

This results in the following buffer:
```
aaa111_aa
```

Now type the following keys:
```
oaaa111_bb<C-c>
```

This **should** result in the following buffer:
```
aaa111_aa
aaa111_bb
```

But it **actually** results in the this buffer:
```
aaa111_aa
aaa
```

The completion script seems to see that there's no match and instead of leaving the typed characters, it deletes several characters.

**Comment by maxboisvert** [comment]
I cannot reproduce this issue, got fixed while fixing another issue.

Maybe in ade56069ce0dada0826ffeddbb99739bd888c6a9
