### ISSUE TITLE
Cursor jumps with closetag.vim

### ISSUE THREAD

**Issue by mamins1376** [maxboisvert/vim-simple-complete#12]
There is an issue with [closetag.vim](https://github.com/vim-closetag/closetag.vim), which completely makes that unuseful. when typing a single `>` in insert mode, the cursor jumps to the upper line and I have to move it back to position. Unfortunately, I'm not able to understand and modify vimscripts and therefore logic behind this plugin to make a pull request.

**Comment by maxboisvert** [comment]
Changed feedkeys mode to `t` and now closetag is working. I was able to reproduce the issue before fixing it.
