### ISSUE TITLE
Auto-complete when only one option

### ISSUE THREAD

**Issue by rncar** [maxboisvert/vim-simple-complete#13]
Thanks for the plugin, really really useful.

Its possible to insert the completation without showing the menu
when we have only one option ?.

**Comment by maxboisvert** [comment]
I think you can add this to your vimrc:

```
set completeopt-=menuone
```

The plugin adds this option [here](https://github.com/maxboisvert/vim-simple-complete/blob/master/plugin/vim-simple-complete.vim#L32). You can read documentation about this option [here](http://vimdoc.sourceforge.net/htmldoc/options.html#'completeopt').
