### ISSUE TITLE
Incompatible with completion continuation

### ISSUE THREAD

**Issue by rafaeln** [maxboisvert/vim-simple-complete#5]
This is a very nice plugin. I like the code a lot too. Beatifully written. You're a poet. I'm even sorry to have to report this problem, since fixing it would possibly make the code uglier. But let's go to it.

Without your plugin, if I have a text file like the following, where the `|` stands for the cursor in insert mode,

```text
This is nice code.
That is not nice code.
Thi|
```

pressing `<c-p><c-x><c-p><c-x><c-p>` gives you this:

```text
This is nice code.
That is not nice code.
This is nice code.|
```

With your plugin, beginning with the same text, you already get the popdown menu indicating the completion to `This`. If I press `<enter>` the completion happens, but then I can't do `<c-x><c-p><c-x><c-p>` to get the continuation. The only way to do continuation, with your plugin, is never pressing `<enter>` to begin with, and then press `<c-p><c-p><c-x><c-p><c-p><c-p><c-x><c-p><c-p><c-p><c-x><c-p><c-p><c-p>`. Way more keystrokes than necessary.

This is just to let you know. I don't quite understand why this happens so and also couldn't find a way to fix the code myself, but thought that you'd like to know about the issue.

**Comment by rafaeln** [comment]
I found that if I remove `noinsert` from `completeopt`, I get the continuation completion fine. The only problem then becomes the fact that autocompletion happens automatically. So, if what I wanted to follow `Thi` with isn't `s`, but `phoon`, then I have to delete the autocompleted `s` before I continue the word. That is, of course, unacceptable. I am now thinking if there is a way to keep `noinsert` out of `completeopt` but then have the plugin automatically delete the automacally inserted completion whenever the user doesn't press enter after it's been automatically done (that is, if the user simply goes on typing).

**Comment by maxboisvert** [comment]
The Enter key `<CR>` binding was removed form this plugin and completion match is not inserted like normal vim completion (pressing tab with this plugin).

The `<CR>` binding was preventing the continuation. Now the continuation is naturally available.

**Comment by rafaeln** [comment]
Maybe there is some previous configuration in my .vimrc preventing me from doing it, but I still get the same result. I still need to press <c-x><c-p><c-p> instead of simply <c-x><c-p> to get completion continuation.
