### ISSUE TITLE
vimwiki conflict

### ISSUE THREAD

**Issue by sdothum** [maxboisvert/vim-simple-complete#8]
Like this plugin very much. The only plugin I currently have problems with is vimwiki (when editing vimwiki files). Pressing enter to select the completion does not insert the selected item. In fact, it inserts a CR instead! Not sure why vimwiki appears to be intercepting the CR before simple-complete and whether anything can be ~~down~~ done to correct this.

**Comment by maxboisvert** [comment]
I have a similar problem with some auto-close plugins. I will look into this!

**Comment by sdothum** [comment]
Great and thanks for the quick reply! One other piece of information you should probably know, if you are unfamiliar with vimwiki, is that the enter key has a specia function in normal mode when the cursor is positioned over a [[link]] item -- pressing enter opens the linked document. One would presume enter in insert mode would just be enter..

**Comment by maxboisvert** [comment]
I removed the `<CR>` mapping, should solve the issue.
